routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('modules.tenderos.index');
});

Route::get('/offline', function(){
    return view('vendor.laravelpwa.offline');
});
//Rutas tenderos
Route::name('tenderos.')->group(function() {
    // Ingreso tenderos
    Route::post('/tenderos/ingreso', [TenderoController::class, 'ingreso'])->name('ingreso');

});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/Tenderos/TenderoController.php
<?php

namespace App\Http\Controllers\Tenderos;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class TenderoController extends BaseController
{
    public function ingreso(Request $request){
        Log::info("Si funciono");
       
    }
    
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{{ secure_asset('serviceworker.js') }}" defer></script>

    <title>Document</title>

    <script>
        // Initialize the service worker
        // if (navigator.serviceWorker.controller) {
        //     console.log('Service worker already registered.')
        // } else {
        //     navigator.serviceWorker.register('serviceworker.js', {
        //     scope: './'
        //     }).then(function(reg) {
        //     console.log('Service worker has been registered for scope:'+ reg.scope);
        //     });
        // }
    </script>
    @laravelPWA
</head>
<body>
    
</body>
</html>

resources/views/modules/tenderos/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>INICIO TENDERO</title>
</head>
<body>
    <h1>HOLA</h1>
</body>
</html>

resources/views/modules/tenderos/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>INGRESO TENDERO</title>
    <script src="{{ secure_asset('serviceworker.js') }}" defer></script>
    <link rel="stylesheet" href="{{ secure_asset('css/tenderos/vistaprincipal.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    
    @laravelPWA

</head>
<body>
    <div class="fondoPrincipal">
        <div class="fondoImg">
            <div class="contenidoinicial animate__animated animate__backInDown">
                <h1 class="MMV">Mi 
                    <span> <img src="{{ secure_asset('images/new/marslogo.svg') }}" class="logo" alt="MARS"> </span>
                </h1>
               <h1 class="MMV1"> Vecino</h1>
            </div>
            {{-- <img src="{{ secure_asset('images/new/vecinologo.png') }}" class="logo" alt="MARS"> --}}
            <form
            method="POST" 
                action="{{ route('tenderos.ingreso') }}"
                class="formIngreso">
                <div class="divIngreso">
                    <img src="{{ secure_asset('images/new/vecino.png') }}" class="vecino" alt="MARS">
                    <div class="titulos">
                        <h1 class="tituloIngreso">¡Bienvenido!</h1></div>
                        <div class="divinput">
                            <input id="identification" type="number" placeholder="Ingrese su cedula" class="inputIngreso" required>
                            <img src="{{ secure_asset('images/new/icon1.png') }}" class="iconocedula" alt="#">
                        </div>
                    <button type="submit" class="btnIngreso animate__animated animate__pulse">Ingresar</button>
                </div>
            </form>
        </div>
    </div>
    
</body>
</html>

resources/views/vistaprueba.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PRUEBA</title>
    <script src="{{ secure_asset('serviceworker.js') }}" defer></script>
    <link rel="stylesheet" href="{{ secure_asset('css/tenderos/vistaprincipal.css') }}">
    
    @laravelPWA

</head>
<body>
    <div class="fondoPrincipal">
        <div class="fondoImg">
            <img src="{{ secure_asset('images/new/marslogo.svg') }}" class="logo" alt="MARS">
            <div class="divIngreso">
                <h1>!Hola tendero, bienvenido!</h1>

            </div>
        </div>
    </div>
    
</body>
</html>